---
- hosts: all
  become: yes

  tasks:

    - name: Ensure epel-release is are installed (RedHat).
      package:
        name: epel-release 
        state: present

    - name: Ensure dependencies for building from source are installed (RedHat).
      become: yes
      become_user: root
      become_method: sudo
      yum:
        name:
          - autoconf
          - automake
          - libtool
          - bison
          - make
          - recode-devel
          - aspell-devel
          - libxml2-devel
          - pkgconfig
          - libmcrypt-devel
          - t1lib-devel
          - libXpm-devel
          - libpng-devel
          - libjpeg-turbo-devel
          - bzip2-devel
          - openssl-devel
          - freetype-devel
          - libicu-devel
          - mariadb-devel
          - gmp-devel
          - expat-devel
        state: present

    - name: Create directory for HTTPD installer directory if it does not exist
      file:
        path: "{{ httpd_installer_dir }}"
        state: directory
        owner: "{{ code_user }}"
        group: "{{ code_user }}"
        mode: "0750"

    - name: Download latest stable version of HTTPD
      get_url:
        url: "{{ httpd_source_url }}"
        dest: "{{ httpd_installer_dir }}"
