---
- hosts: all
  become: yes

  tasks:

    - name: Ensure epel-release is are installed (RedHat).
      package:
        name: epel-release 
        state: present

    - name: Ensure dependencies for building from source are installed (RedHat).
      become: yes
      become_user: root
      become_method: sudo
      yum:
        name:
          - autoconf
          - automake
          - libtool
          - bison
          - make
          - recode-devel
          - aspell-devel
          - libxml2-devel
          - pkgconfig
          - libmcrypt-devel
          - t1lib-devel
          - libXpm-devel
          - libpng-devel
          - libjpeg-turbo-devel
          - bzip2-devel
          - openssl-devel
          - freetype-devel
          - libicu-devel
          - mariadb-devel
          - gmp-devel
          - expat-devel
        state: present

    - name: Create directory for HTTPD installer directory if it does not exist
      file:
        path: "{{ httpd_installer_dir }}"
        state: directory
        owner: "{{ code_user }}"
        group: "{{ code_user }}"
        mode: "0750"

    - name: Download latest stable version of HTTPD
      get_url:
        url: "{{ httpd_source_url }}"
        dest: "{{ httpd_installer_dir }}"

    - name: Extract downloaded HTTPD tar.gz file
      unarchive:
        src: "{{ httpd_installer_dir }}/{{ httpd_source_version }}.tar.gz"
        dest: "{{ httpd_installer_dir }}"
        remote_src: yes

    - name: Ensure HTTPD installation path exists.
      file:
        path: "{{ httpd_install_path }}"
        state: directory
        mode: "0750"

    - name: Download latest stable version of APR
      get_url:
        url: "{{ apr_source_url }}{{ apr_source_version }}.tar.gz"
        dest: "{{ httpd_installer_dir }}"
        checksum: "{{ apr_source_checksum }}"

    - name: Ensure GML Source DIR set correct permission
      shell: sh -c "{{ item }}"
      with_items:
        - "sudo chown -R {{ code_user }}:{{ code_user }} /export/home"
        - "sudo chmod 750 /export/home"

    - name: Extract downloaded APR tar.gz file
      unarchive:
        src: "{{ httpd_installer_dir }}{{ apr_source_version }}.tar.gz"
        dest: "{{ httpd_installer_dir }}"
        remote_src: yes

    - name: Download latest stable version of APR-UTIL
      get_url:
        url: "{{ apr_source_url }}{{ apr_util_source_version }}.tar.gz"
        dest: "{{ httpd_installer_dir }}"
        checksum: "{{ apr_util_source_checksum }}"

    - name: Ensure GML Source DIR set correct permission
      shell: sh -c "{{ item }}"
      with_items:
        - "sudo chown -R {{ code_user }}:{{ code_user }} /export/home"
        - "sudo chmod 750 /export/home"

    - name: Extract downloaded APR-UTIL tar.gz file
      unarchive:
        src: "{{ httpd_installer_dir }}{{ apr_util_source_version }}.tar.gz"
        dest: "{{ httpd_installer_dir }}"
        remote_src: yes

    - name: Move APR inside HTTPD installation dir
      command: mv {{ httpd_installer_dir }}{{ apr_source_version }} {{ httpd_installer_dir }}/{{ httpd_source_version }}/srclib/apr

    - name: Move APR-UTIL inside HTTPD installation dir
      command: mv {{ httpd_installer_dir }}{{ apr_util_source_version }} {{ httpd_installer_dir }}/{{ httpd_source_version }}/srclib/apr-util

    - name: Run configure script.
      command: >
        {{ httpd_source_configure_command }}
        chdir={{ httpd_installer_dir }}/{{ httpd_source_version }}

    - name: Make and install HTTPD.
      command: >
        {{ item }}
        chdir={{ httpd_installer_dir }}/{{ httpd_source_version }}
      with_items:
        - make
        - make install
      become: yes
      become_method: sudo
      become_user: root

    - name: Ensure GML Source DIR set correct permission
      shell: sh -c "{{ item }}"
      with_items:
        - "sudo chown -R {{ code_user }}:{{ code_user }} /export/home"
        - "sudo chmod 750 /export/home"
