---
- hosts: all
  become: yes

  tasks:

    - name:Ensure epel-release is are installed (RedHat).
      package:
        name:
          - epel-release
        state: present
      when: ansible_os_family == 'RedHat'
